#!/bin/bash
# Phase D — continuation of Phase C with the v6_all data mix.
#
# What's NEW in this phase vs Phase C:
#   1. FIM augmentation on code sources (fim_rate=0.5)
#   2. ~10% Phi-style synthetic (signature+docstring → body) data
#      (data/synthetic_pyfunc.jsonl, generated by
#      gen_synthetic_pyfunc_data.py)
#   3. ~2% self-debug (broken/error/fix) triples woven in as natural
#      code text (data/pretrain_repair_corpus.jsonl, built by
#      build_pretrain_repair_corpus.py)
#   4. In-process HumanEval probe every 1B tokens (50-problem subset)
#      so we can see capability move during training, not just LM ppl.
#
# Same arch, optimizer, gist loss, gate, PKM, WM as Phase C — we are
# only changing what the model SEES during training, not how.
#
# Resumes from pretrain_phase_c.pt (5.28B tokens) → 23000 + 13000 =
# 36000 steps ≈ 8.25 B tokens total. Adds 3 B new tokens on the
# improved mix (~13 h wall on single 5090 at the Phase C tok/s).
#
# Prerequisites (check before launching):
#   * checkpoints/pretrain_phase_c.pt exists
#   * data/synthetic_pyfunc.jsonl exists (run gen_synthetic_pyfunc_data.py)
#   * data/pretrain_repair_corpus.jsonl exists (run
#     build_pretrain_repair_corpus.py)
#   * data/probe_humaneval_50.jsonl exists (run build_probe_dataset.py)

set -e
cd /home/knielsen/ml/parallel-ss-dep
export PYTHONPATH=$PYTHONPATH:.
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
mkdir -p runs checkpoints

# Sanity-check prerequisites before launching a 13-hour run.
for f in checkpoints/pretrain_phase_c.pt \
         data/synthetic_pyfunc.jsonl \
         data/pretrain_repair_corpus.jsonl \
         data/probe_humaneval_50.jsonl \
         configs/pretrain_mix_v6_all.yaml; do
  if [[ ! -e "$f" ]]; then
    echo "ERROR: missing prerequisite: $f"
    exit 1
  fi
done

CUDA_VISIBLE_DEVICES=${GPU:-0} nohup .venv/bin/python -u experiments/train_lm.py \
    --arch deltanet \
    --d_model 896 --n_layers 10 --d_head 64 --n_heads 14 \
    --feedback film \
    --feedback_pairs "0,5;1,6;2,7;3,8;4,9" \
    --feedback_self_k 3 \
    --feedback_self_k_warmup_steps 0 \
    --output_gate \
    --gate_entropy_aux_weight 0.1 \
    --gate_entropy_aux_temperature 2.0 \
    --use_memory --mem_size 1024 \
    --use_pkm --pkm_after_layer 5 \
    --pkm_n_heads 4 --pkm_n_keys 256 --pkm_k_dim 128 --pkm_top_k 32 \
    --pkm_use_output_gate \
    --pkm_epsilon_start 0.0 --pkm_epsilon_warmup_steps 0 \
    --pkm_value_init_std 1.0 \
    --pkm_score_norm layer \
    --pkm_diversity_weight 0.01 \
    --pkm_alpha_floor_start 0.0 --pkm_alpha_floor_warmup_steps 0 \
    --pkm_value_lr_mult 100.0 \
    --gist_loss_weight 0.1 --gist_horizons "16,64,256" \
    --data_mix configs/pretrain_mix_v6_all.yaml \
    --tokenizer HuggingFaceTB/SmolLM2-135M \
    --think_burst_prob 0.5 --think_max_bursts 2 --think_max_burst_depth 6 \
    --T 2048 --batch 14 --grad_accum 8 \
    --activation_checkpointing \
    --bf16 --tf32 --compile \
    --alpha_wd 0.0 --wd 0.01 \
    --grad_clip 1.0 --z_loss 1e-4 \
    --mask_eos_in_targets \
    --gate_floor_min 0.5 --gate_warmup_steps 0 \
    --optimizer muon --lr 1.4e-3 --lr_muon 5e-3 \
    --lr_schedule wsd --warmup_steps 200 --lr_decay_frac 0.15 \
    --load_ckpt checkpoints/pretrain_phase_c.pt \
    --start_step 23000 \
    --steps 36000 \
    --val_every 200 --log_every 20 \
    --probe_humaneval_every_tokens 1000000000 \
    --probe_humaneval_path data/probe_humaneval_50.jsonl \
    --probe_humaneval_max_gen 192 \
    --mid_eval_every_tokens 1000000000 \
    --mid_eval_save_only \
    --save_ckpt checkpoints/pretrain_phase_d.pt \
    --tb_dir runs/tb/pretrain_phase_d \
    > runs/pretrain_phase_d.log 2>&1 &
echo "Launched Phase D pretrain on GPU ${GPU:-0} (PID $!)"
echo "Watch:  tail -f runs/pretrain_phase_d.log"
